# Generated by Django 5.0 on 2024-01-31 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Register_Login', '0009_paymenttermsupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('account_type', models.CharField(max_length=2)),
                ('bankname', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=15, unique=True)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('swift_code', models.CharField(max_length=11)),
                ('branch_name', models.CharField(max_length=100)),
                ('cheque_book_range', models.CharField(max_length=5)),
                ('enable_cheque_printing', models.CharField(max_length=3)),
                ('cheque_printing_configuration', models.CharField(max_length=3)),
                ('mailing_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('pin', models.CharField(max_length=6)),
                ('pan_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('registration_type', models.CharField(max_length=15)),
                ('gst_num', models.CharField(blank=True, max_length=15)),
                ('alter_gst_details', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('amount_type', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=10)),
                ('bank_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.bankaccount')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('logindetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnk_name', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('bnk_branch', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('bnk_acno', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('bnk_ifsc', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('bnk_bal_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Debit', max_length=220)),
                ('bnk_opnbal', models.FloatField(blank=True, null=True)),
                ('bnk_bal', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='bank/')),
                ('status', models.TextField(default='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.banking'),
        ),
        migrations.CreateModel(
            name='loan_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.IntegerField()),
                ('lender_bank', models.CharField(max_length=255)),
                ('loan_date', models.DateField()),
                ('payment_method', models.CharField(max_length=255)),
                ('upi_id', models.CharField(max_length=255)),
                ('cheque', models.CharField(max_length=255)),
                ('loan_rec_bank_acc', models.CharField(max_length=255)),
                ('processing_method', models.CharField(max_length=255)),
                ('processing_fee', models.IntegerField()),
                ('interest', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('bank_holder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.bankaccount')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('logindetails', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
