# Generated by Django 5.0 on 2024-02-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0003_remove_repayment_due_bank_repayment_due_bank_holder'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment_due',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.loan_account'),
        ),
    ]
