# Generated by Django 5.0 on 2024-02-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0005_newloan'),
    ]

    operations = [
        migrations.AddField(
            model_name='newloan',
            name='interest_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
