# Generated by Django 5.0 on 2024-02-08 06:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0006_newloan_interest_amount'),
        ('Register_Login', '0009_paymenttermsupdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repayment_due',
            name='bank_holder',
        ),
        migrations.RemoveField(
            model_name='repayment_due',
            name='company',
        ),
        migrations.RemoveField(
            model_name='repayment_due',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='repayment_due',
            name='login_details',
        ),
        migrations.CreateModel(
            name='LoanRepayemnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.IntegerField(blank=True, null=True)),
                ('interest_amount', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=255)),
                ('upi_id', models.CharField(max_length=255)),
                ('cheque', models.CharField(max_length=255)),
                ('payment_date', models.DateField(default=datetime.date.today)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.loan_account')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.DeleteModel(
            name='newloan',
        ),
        migrations.DeleteModel(
            name='repayment_due',
        ),
    ]
