# Generated by Django 5.0 on 2024-02-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_remove_repayment_due_bank_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayemnt',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
