# Generated by Django 5.0 on 2024-02-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0008_loanrepayemnt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_account',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
