# Generated by Django 5.0 on 2024-02-13 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0009_loan_account_balance'),
        ('Register_Login', '0009_paymenttermsupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_account',
            name='account_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='processing_acc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='processing_cheque',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='processing_upi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='term',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Loan_Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('term', models.CharField(blank=True, max_length=255, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
            ],
        ),
        migrations.AddField(
            model_name='loan_account',
            name='loan_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.loan_term'),
        ),
    ]
