# Generated by Django 5.0 on 2024-02-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0010_loan_account_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_account',
            name='status',
            field=models.TextField(default='Active'),
        ),
    ]
