# Generated by Django 5.0 on 2024-02-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0014_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.loan_account'),
        ),
    ]
