# Generated by Django 5.0 on 2024-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0015_comments_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayemnt',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
