# Generated by Django 5.0 on 2024-02-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0016_loanrepayemnt_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_account',
            old_name='loan_rec_bank_acc',
            new_name='payment_accountnumber',
        ),
    ]
