# Generated by Django 5.0 on 2024-03-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0020_alter_loan_account_cheque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='status',
            field=models.TextField(default='Active'),
        ),
    ]
